apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: stage-asia-hello-world-app-uat-test-stage-red
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://asia-host:3306/mysqlrty123
  ENVIRONMENT: Stage
  REGION: Asia
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"