apiVersion: v1
kind: Namespace
metadata:
  name: "dev-west-us-hw-dev" 
  labels:
    environment: "dev"
    workspace: "kaizen-team"
    workload: "hw"
    deploymentTarget: "hw-dev"
    someLabel: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hw-sa"
  namespace: "dev-west-us-hw-dev"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: "dev-west-us-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  limits:
  - max:
      storage: 64Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pvc-resource-quota
  namespace: "dev-west-us-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  hard:
    requests.storage: 64Gi
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "hw-spc"
  namespace: "dev-west-us-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  provider: azure
  clientID: "<no value>"
  parameters:
    keyvaultName: "<no value>"
    objects: |
      array:
          null
    tenantID: "<no value>"
---

