apiVersion: v1
kind: Namespace
metadata:
  name: "dev-west-us-hello-world-app-functional-test-dev-green" 
  labels:
    environment: "dev"
    workspace: "kaizen-team"
    workload: "hello-world-app"
    deploymentTarget: "hello-world-app-functional-test-dev-green"
    someLabel: some-value
