apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: stage-eu-hello-world-app-uat-test-stage-green
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://eu-host:3306/mysqlrty123
  ENVIRONMENT: Stage
  REGION: EU
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"