apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: stage-west-us-hello-world-app-uat-test-stage-green
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://us-host:3306/mysqlrty123
  ENVIRONMENT: Stage
  REGION: West US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"