---
- hosts: localhost
  tasks:
  - name: install cron job (ansible-pull)
    cron:
      name: hw-dev
      minute: "*/1"
      user: dev-hw-dev
      job: |
        ansible-pull -o -U https://github.com/eedorenko/hello-world-gitops -C dev ./hw > $HOME/ansible-pull-hw-dev.log 2>$HOME/ansible-pull-hw-dev.err
