apiVersion: v1
kind: Namespace
metadata:
  name: "dev-asia-ct-functional-test-dev-red" 
  labels:
    environment: "dev"
    workspace: "demo-team"
    workload: "ct"
    deploymentTarget: "ct-functional-test-dev-red"
    someLabel: some-value
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: environment=dev          
