apiVersion: v1
kind: Namespace
metadata:
  name: "prod-plk-chicken-detection-prod-gray" 
  labels:
    environment: "prod"
    workspace: "dt"
    workload: "chicken-detection"
    deploymentTarget: "chicken-detection-prod-gray"
    someLabel: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "chicken-detection-sa"
  namespace: "prod-plk-chicken-detection-prod-gray"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: "prod-plk-chicken-detection-prod-gray"
  labels:
    environment: "prod"
    workload: "chicken-detection"
spec:
  limits:
  - max:
      storage: 64Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pvc-resource-quota
  namespace: "prod-plk-chicken-detection-prod-gray"
  labels:
    environment: "prod"
    workload: "chicken-detection"
spec:
  hard:
    requests.storage: 64Gi