apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-west-us-burger-detection-dev
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://us-host:3306/mysqlrty1234
  ENVIRONMENT: Dev
  REGION: West US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "true"
  brand-cke-brand_id: cke
