apiVersion: v1
kind: Namespace
metadata:
  name: "dev-east-us-burger-detection-dev" 
  labels:
    environment: "dev"
    workspace: "dt"
    workload: "burger-detection"
    deploymentTarget: "burger-detection-dev"
    someLabel: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "burger-detection-sa"
  namespace: "dev-east-us-burger-detection-dev"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: "dev-east-us-burger-detection-dev"
  labels:
    environment: "dev"
    workload: "burger-detection"
spec:
  limits:
  - max:
      storage: 64Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pvc-resource-quota
  namespace: "dev-east-us-burger-detection-dev"
  labels:
    environment: "dev"
    workload: "burger-detection"
spec:
  hard:
    requests.storage: 64Gi
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "burger-detection-spc"
  namespace: "dev-east-us-burger-detection-dev"
  labels:
    environment: "dev"
    workload: "burger-detection"
spec:
  provider: azure

  parameters:
    keyvaultName: "<no value>"
    objects: |
      array:
          null
    tenantID: "<no value>"
---

