apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-eu-ct-functional-test-dev-red
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://eu-host:3306/mysqlrty123
  ENVIRONMENT: Dev
  REGION: EU
  SOME_COMMON_ENVIRONMENT_VARIABLE: "true"