apiVersion: v1
kind: Namespace
metadata:
  name: "prod-cke-burger-detection-prod-gray" 
  labels:
    environment: "prod"
    workspace: "dt"
    workload: "burger-detection"
    deploymentTarget: "burger-detection-prod-gray"
    someLabel: some-value
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: environment=prod          
