apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: prod-cke-burger-detection-prod-gray
data:
  ENVIRONMENT: Prod
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"
  brand_id: cke
  vision_dayparts:
    breakfast: 8AM - 10AM