apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: prod-cke-burger-detection-prod-gray
data:
  ENVIRONMENT: Prod
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"
  brand_id: cke1
  model_class_mapping: '{0:patty, 1:in_progress, 2:completed_burger, 3:packaged_burger}'
  model_confidence_threshold: "0.75"
  task_type: object_detection
  vision_dayparts: breakfast 8AM - 10AM
  worker_cameras: '["packaging1"]'
  worker_object_inactivity_threshold: 120s
  worker_operating_fps: "6"
  worker_tracker_distance_function: kou
  worker_tracker_distance_threshold: "0.75"
  worker_tracker_name: norfair
  worker_zones: '["packaging1/assembly_table"]'
  worker_zones_rentry_buffer_time: 2s
  worker_zones_zone_boundary_threshold: 5 pixels
