apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prod-gray.demo-team.kos.burger-detection.burger-detection-prod-gray
  namespace: flux-system
spec:
  interval: 30s
  url: "https://github.com/eedorenko/mlops-gitops-gitops"
  ref:
    branch: "prod-gray"
  secretRef:
      name: repo-secret    
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod-gray.demo-team.kos.burger-detection.burger-detection-prod-gray
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: "prod-cke-burger-detection-prod-gray"
  sourceRef:
    kind: GitRepository
    name: prod-gray.demo-team.kos.burger-detection.burger-detection-prod-gray
  path: "./burger-detection" 
  prune: true
