apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-east-us-hw-functional-test-dev-gray-east-us
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://us-host:3306/mysqlrty123
  ENVIRONMENT: Dev
  REGION: East US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"