apiVersion: v1
kind: Namespace
metadata:
  name: "dev-eu-hw-dev" 
  labels:
    environment: "dev"
    workspace: "kaizen-team"
    workload: "hw"
    deploymentTarget: "hw-dev"
    someLabel: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hw-sa"
  namespace: "dev-eu-hw-dev"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: "dev-eu-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  limits:
  - max:
      storage: 64Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pvc-resource-quota
  namespace: "dev-eu-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  hard:
    requests.storage: 64Gi
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "hw-spc"
  namespace: "dev-eu-hw-dev"
  labels:
    environment: "dev"
    workload: "hw"
spec:
  provider: azure        
  parameters:
    clientID: "332f57f9-6de8-4929-ad1e-f1f3015ee0ae"
    keyvaultName: "ansible-secret-key-vault"
    objects: |
      array:
          - |
            objectName: application-secret
            objectType: secret
          - |
            objectName: acr-secret
            objectType: secret
          - |
            objectName: git-hub-token
            objectType: secret
    tenantID: "16b3c013-d300-468d-ac64-7eda0820b6d3"
---

      

      

apiVersion: secret-sync.x-k8s.io/v1alpha1
kind: SecretSync
metadata:
  name: "application-secret"
  namespace: dev-eu-hw-dev
spec:
  serviceAccountName: "hw-sa"
  secretProviderClassName: "hw-spc"
  secretObject:
    type: "Opaque"
    data: 
      - sourcePath: application-secret
        targetKey: application-secret-value

apiVersion: secret-sync.x-k8s.io/v1alpha1
kind: SecretSync
metadata:
  name: "gh-repo-secret"
  namespace: dev-eu-hw-dev
spec:
  serviceAccountName: "hw-sa"
  secretProviderClassName: "hw-spc"
  secretObject:
    type: "Opaque"
    data: 
      - sourcePath: git-hub-user
        targetKey: username
      - sourcePath: git-hub-token
        targetKey: password
  

