apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-eu-hw-dev
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://eu-db-host:3308/mysql
  ENVIRONMENT: Dev
  REGION: EU
  SOME_COMMON_ENVIRONMENT_VARIABLE: "true"
  azureTenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
  keyVaultSecrets: |
    - |
      objectName: application-secret
      objectType: secret
  keyvaultName: ansible-secret-key-vault
  managedIdentityId: 332f57f9-6de8-4929-ad1e-f1f3015ee0ae
  secretObjects: |
    - data:
      - sourcePath: application-secret
        targetKey: application-secret-value
      type: Opaque
