apiVersion: v1
kind: Namespace
metadata:
  name: "stage-west-us-chicken-detection-stage" 
  labels:
    environment: "stage"
    workspace: "demo-team"
    workload: "chicken-detection"
    deploymentTarget: "chicken-detection-stage"
    someLabel: some-value
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: environment=stage          
