apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: dev-west-us-hw-functional-test-dev-green
data:
  CLUSTER_NAME: Factory Cluster
  DATABASE_URL: mysql://us-host:3306/mysqlrty123
  ENVIRONMENT: Dev
  REGION: West US
  SOME_COMMON_ENVIRONMENT_VARIABLE: "false"