apiVersion: v1
kind: Namespace
metadata:
  name: "stage-west-us-entree-detection-stage" 
  labels:
    environment: "stage"
    workspace: "dt"
    workload: "entree-detection"
    deploymentTarget: "entree-detection-stage"
    someLabel: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "entree-detection-sa"
  namespace: "stage-west-us-entree-detection-stage"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: "stage-west-us-entree-detection-stage"
  labels:
    environment: "stage"
    workload: "entree-detection"
spec:
  limits:
  - max:
      storage: 64Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pvc-resource-quota
  namespace: "stage-west-us-entree-detection-stage"
  labels:
    environment: "stage"
    workload: "entree-detection"
spec:
  hard:
    requests.storage: 64Gi