apiVersion: v1
kind: Namespace
metadata:
  name: "stage-east-us-hw-performance-test-stage" 
  labels:
    environment: "stage"
    workspace: "kaizen-team"
    workload: "hw"
    deploymentTarget: "hw-performance-test-stage"
    someLabel: some-value
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: environment=stage          
